import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireAuthFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import { Prisma } from '@prisma/client'
import {
  apiCreated,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuthFromRequest(request)
    const body = await request.json()
    const { accountId, type, amount, date, reference, notes } = body

    if (!accountId || !type || amount == null) {
      return apiBadRequest('accountId, type, and amount are required')
    }

    const validTypes = ['DEPOSIT', 'WITHDRAWAL']
    if (!validTypes.includes(type)) {
      return apiBadRequest(`type must be one of: ${validTypes.join(', ')}`)
    }

    if (Number(amount) <= 0) {
      return apiBadRequest('Amount must be positive')
    }

    const account = await prisma.savingsAccount.findUnique({
      where: { id: accountId },
      include: {
        member: {
          include: {
            samity: { include: { branch: true } },
          },
        },
      },
    })

    if (!account) {
      return apiNotFound('Savings account not found')
    }

    // Tenant isolation
    if (account.member.samity.branch.organizationId !== auth.organizationId) {
      return apiNotFound('Savings account not found')
    }

    if (!account.isActive) {
      return apiBadRequest('Savings account is inactive')
    }

    const txnAmount = Number(amount)
    const currentBalance = Number(account.balance)

    // Validate balance for withdrawal
    if (type === 'WITHDRAWAL' && txnAmount > currentBalance) {
      return apiBadRequest(`Insufficient balance. Available: ${currentBalance}`)
    }

    const balanceAfter = type === 'DEPOSIT'
      ? currentBalance + txnAmount
      : currentBalance - txnAmount

    const organizationId = account.member.samity.branch.organizationId
    const txnDate = date ? new Date(date) : new Date()

    const [transaction] = await prisma.$transaction([
      prisma.savingsTransaction.create({
        data: {
          accountId,
          date: txnDate,
          type,
          amount: txnAmount,
          balanceAfter,
          reference: reference || null,
          transactedById: auth.userId,
          notes: notes || null,
        },
        select: {
          id: true,
          accountId: true,
          date: true,
          type: true,
          amount: true,
          balanceAfter: true,
          reference: true,
          createdAt: true,
        },
      }),
      prisma.savingsAccount.update({
        where: { id: accountId },
        data: {
          balance: balanceAfter,
          ...(type === 'DEPOSIT'
            ? { totalDeposited: { increment: txnAmount } }
            : { totalWithdrawn: { increment: txnAmount } }),
        },
      }),
    ])

    // Auto-create JE for savings transaction
    let journalEntryId: string | null = null

    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: { organizationId, isCurrent: true },
      select: { id: true },
    })

    if (fiscalYear && txnAmount > 0) {
      const cashAccount = await prisma.account.findFirst({
        where: { organizationId, isBankAccount: true, isActive: true, isGroup: false, deletedAt: null },
        select: { id: true },
      })

      const savingsLiabilityAccount = await prisma.account.findFirst({
        where: { organizationId, accountType: { in: ['LIABILITY', 'INCOME'] }, isActive: true, isGroup: false, deletedAt: null },
        select: { id: true },
      })

      if (cashAccount && savingsLiabilityAccount) {
        const entryNo = await generateNextNumber(organizationId, 'journal_entry')
        const now = new Date()

        const debitAccountId = type === 'DEPOSIT' ? cashAccount.id : savingsLiabilityAccount.id
        const creditAccountId = type === 'DEPOSIT' ? savingsLiabilityAccount.id : cashAccount.id

        const je = await prisma.journalEntry.create({
          data: {
            entryNo,
            date: txnDate,
            description: `Savings ${type.toLowerCase()} — account ${account.accountNo || accountId}`,
            fiscalYearId: fiscalYear.id,
            totalDebit: new Prisma.Decimal(txnAmount),
            totalCredit: new Prisma.Decimal(txnAmount),
            status: 'APPROVED',
            isAutoGenerated: true,
            sourceModule: 'savings',
            sourceId: transaction.id,
            createdById: auth.userId,
            approvedById: auth.userId,
            approvedAt: now,
            postedAt: now,
            lines: {
              create: [
                {
                  accountId: debitAccountId,
                  description: `Savings ${type.toLowerCase()} — debit`,
                  debit: new Prisma.Decimal(txnAmount),
                  credit: new Prisma.Decimal(0),
                },
                {
                  accountId: creditAccountId,
                  description: `Savings ${type.toLowerCase()} — credit`,
                  debit: new Prisma.Decimal(0),
                  credit: new Prisma.Decimal(txnAmount),
                },
              ],
            },
          },
        })

        journalEntryId = je.id

        await prisma.savingsTransaction.update({
          where: { id: transaction.id },
          data: { journalEntryId: je.id },
        })
      }
    }

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId,
      userId: auth.userId,
      action: 'CREATE',
      module: 'microfinance',
      resource: 'savings_transaction',
      resourceId: transaction.id,
      description: `Created savings ${type.toLowerCase()} of ${txnAmount} on account ${accountId}`,
      newValues: { type, amount: txnAmount, balanceAfter, accountId },
      ...auditCtx,
    })

    return apiCreated({ ...transaction, journalEntryId })
  } catch (error) {
    return handleRouteError(error)
  }
}
