/**
 * Concurrency test for vendor payment posting.
 * Verifies the fix for: when two payments race, the final invoice status
 * must reflect the actual outstanding (PAID when 0, PARTIALLY_PAID otherwise).
 *
 * Run: pnpm tsx --env-file=.env prisma/test-concurrent-payments.ts
 */
import { PrismaClient, Prisma } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import pg from 'pg'

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

interface PostPaymentParams {
  invoiceId: string
  amount: number
  fyId: string
  bankId: string
  glId: string
  apId: string
  paidById: string
  organizationId: string
  tag: string
}

// Mirrors the FIXED route handler: newStatus computed inside the TX from freshInvoice.
async function postPaymentLikeRoute(p: PostPaymentParams) {
  return prisma.$transaction(async (tx) => {
    const fresh = await tx.vendorInvoice.findUnique({
      where: { id: p.invoiceId },
      select: { outstandingAmount: true, status: true, organizationId: true },
    })
    if (!fresh) throw new Error('not found')
    if (fresh.status !== 'APPROVED' && fresh.status !== 'PARTIALLY_PAID') {
      throw new Error(`status=${fresh.status}`)
    }
    if (p.amount > Number(fresh.outstandingAmount)) {
      throw new Error(`amount ${p.amount} > outstanding ${Number(fresh.outstandingAmount)}`)
    }

    // FIXED: compute newStatus from freshInvoice inside the TX
    const newOutstanding = Math.round((Number(fresh.outstandingAmount) - p.amount) * 100) / 100
    const newStatus = newOutstanding <= 0 ? 'PAID' : 'PARTIALLY_PAID'

    const payment = await tx.vendorPayment.create({
      data: {
        organizationId: p.organizationId,
        paymentNo: `${p.tag}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        invoiceId: p.invoiceId,
        paymentDate: new Date(),
        paymentMethod: 'BANK_TRANSFER',
        bankAccountId: p.bankId,
        amount: new Prisma.Decimal(p.amount),
        netPaid: new Prisma.Decimal(p.amount),
        status: 'APPROVED',
        paidById: p.paidById,
      },
    })
    await tx.journalEntry.create({
      data: {
        entryNo: `JE-${p.tag}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        date: new Date(),
        description: `concurrency test ${p.tag}`,
        fiscalYearId: p.fyId,
        totalDebit: new Prisma.Decimal(p.amount),
        totalCredit: new Prisma.Decimal(p.amount),
        status: 'APPROVED',
        isAutoGenerated: true,
        sourceModule: 'VENDOR_PAYMENT',
        sourceId: payment.id,
        createdById: p.paidById,
        approvedById: p.paidById,
        approvedAt: new Date(),
        postedAt: new Date(),
        lines: {
          create: [
            { accountId: p.apId, debit: new Prisma.Decimal(p.amount), credit: new Prisma.Decimal(0) },
            { accountId: p.glId, debit: new Prisma.Decimal(0), credit: new Prisma.Decimal(p.amount) },
          ],
        },
      },
    })
    await tx.bankAccount.update({
      where: { id: p.bankId },
      data: { currentBalance: { decrement: new Prisma.Decimal(p.amount) } },
    })
    await tx.vendorInvoice.update({
      where: { id: p.invoiceId },
      data: {
        paidAmount: { increment: new Prisma.Decimal(p.amount) },
        outstandingAmount: { decrement: new Prisma.Decimal(p.amount) },
        status: newStatus,
      },
    })
    return { newStatus, newOutstanding }
  }, { isolationLevel: Prisma.TransactionIsolationLevel.ReadCommitted })
}

async function main() {
  const org = await prisma.organization.findFirst({ where: { slug: 'cssbd' } })
  if (!org) throw new Error('no org')
  const admin = await prisma.user.findFirst({ where: { organizationId: org.id, role: { name: 'ADMIN' } } })
  const fy = await prisma.fiscalYear.findFirst({ where: { organizationId: org.id, isCurrent: true } })
  const ba = await prisma.bankAccount.findFirst({
    where: { organizationId: org.id, isActive: true, glAccountId: { not: null } },
    include: { glAccount: true },
  })
  const ap = await prisma.account.findFirst({ where: { organizationId: org.id, code: '201002' } })
  const vendor = await prisma.vendor.findFirst({ where: { organizationId: org.id, isApproved: true, isActive: true } })
  const expense = await prisma.account.findFirst({ where: { organizationId: org.id, type: 'EXPENSE', isGroup: false } })
  if (!admin || !fy || !ba || !ap || !vendor || !expense) throw new Error('missing master data')

  const runId = `CONC-${Date.now()}`

  // Build a quick chain: PR → PO → GRN → AP credit JE → APPROVED invoice
  const pr = await prisma.purchaseRequisition.create({
    data: {
      prNo: `PR-${runId}`,
      requestedById: admin.id,
      date: new Date(),
      totalEstimate: new Prisma.Decimal(10000),
      status: 'APPROVED',
      submittedAt: new Date(),
      approvedById: admin.id,
      approvedAt: new Date(),
      lines: {
        create: [
          {
            description: 'Concurrency test',
            unit: 'svc',
            quantity: new Prisma.Decimal(10),
            estimatedPrice: new Prisma.Decimal(1000),
            totalEstimate: new Prisma.Decimal(10000),
            itemType: 'SERVICE_OR_EXPENSE',
            accountId: expense.id,
          },
        ],
      },
    },
    include: { lines: true },
  })
  const po = await prisma.purchaseOrder.create({
    data: {
      poNo: `PO-${runId}`,
      vendorId: vendor.id,
      date: new Date(),
      totalAmount: new Prisma.Decimal(10000),
      status: 'COMPLETED',
      lines: {
        create: pr.lines.map((l) => ({
          prLineId: l.id,
          description: l.description,
          unit: l.unit,
          quantity: l.quantity,
          unitPrice: l.estimatedPrice,
          totalPrice: l.totalEstimate,
          receivedQty: l.quantity,
          itemType: 'SERVICE_OR_EXPENSE' as const,
          accountId: expense.id,
        })),
      },
    },
    include: { lines: true },
  })
  const grn = await prisma.goodsReceipt.create({
    data: {
      grnNo: `GRN-${runId}`,
      poId: po.id,
      vendorId: vendor.id,
      receivedById: admin.id,
      date: new Date(),
      status: 'ACCEPTED',
      lines: {
        create: [
          {
            poLineId: po.lines[0].id,
            description: 'X',
            quantityOrdered: po.lines[0].quantity,
            quantityReceived: po.lines[0].quantity,
            quantityAccepted: po.lines[0].quantity,
            quantityRejected: new Prisma.Decimal(0),
            itemType: 'SERVICE_OR_EXPENSE' as const,
            accountId: expense.id,
          },
        ],
      },
    },
  })
  await prisma.journalEntry.create({
    data: {
      entryNo: `JE-GRN-${runId}`,
      date: new Date(),
      description: 'GRN credit',
      fiscalYearId: fy.id,
      totalDebit: new Prisma.Decimal(10000),
      totalCredit: new Prisma.Decimal(10000),
      status: 'APPROVED',
      isAutoGenerated: true,
      sourceModule: 'PROCUREMENT_GRN',
      sourceId: grn.id,
      createdById: admin.id,
      approvedById: admin.id,
      approvedAt: new Date(),
      postedAt: new Date(),
      lines: {
        create: [
          { accountId: expense.id, debit: new Prisma.Decimal(10000), credit: new Prisma.Decimal(0) },
          { accountId: ap.id, debit: new Prisma.Decimal(0), credit: new Prisma.Decimal(10000) },
        ],
      },
    },
  })
  const invoice = await prisma.vendorInvoice.create({
    data: {
      organizationId: org.id,
      invoiceNo: `INV-${runId}`,
      invoiceDate: new Date(),
      vendorId: vendor.id,
      poId: po.id,
      grossAmount: new Prisma.Decimal(10000),
      netPayable: new Prisma.Decimal(10000),
      outstandingAmount: new Prisma.Decimal(10000),
      status: 'APPROVED',
      approvedById: admin.id,
      approvedAt: new Date(),
      createdById: admin.id,
      grns: { create: [{ grnId: grn.id, acceptedAmount: new Prisma.Decimal(10000) }] },
    },
  })

  console.log(`Setup done. Invoice=${invoice.invoiceNo} outstanding=10000 — firing two concurrent payments (6000 + 4000)`)

  const [r1, r2] = await Promise.allSettled([
    postPaymentLikeRoute({
      invoiceId: invoice.id,
      amount: 6000,
      fyId: fy.id,
      bankId: ba.id,
      glId: ba.glAccount!.id,
      apId: ap.id,
      paidById: admin.id,
      organizationId: org.id,
      tag: 'A',
    }),
    postPaymentLikeRoute({
      invoiceId: invoice.id,
      amount: 4000,
      fyId: fy.id,
      bankId: ba.id,
      glId: ba.glAccount!.id,
      apId: ap.id,
      paidById: admin.id,
      organizationId: org.id,
      tag: 'B',
    }),
  ])

  console.log('Payment A:', r1.status, r1.status === 'fulfilled' ? r1.value : r1.reason?.message)
  console.log('Payment B:', r2.status, r2.status === 'fulfilled' ? r2.value : r2.reason?.message)

  const final = await prisma.vendorInvoice.findUnique({ where: { id: invoice.id } })
  console.log(`Final invoice: status=${final!.status} paid=${Number(final!.paidAmount)} outstanding=${Number(final!.outstandingAmount)}`)

  const both = r1.status === 'fulfilled' && r2.status === 'fulfilled'
  if (both && final!.status === 'PAID' && Math.abs(Number(final!.outstandingAmount)) < 0.01) {
    console.log('✓ PASS: both succeeded, final state PAID + outstanding=0')
  } else if (!both) {
    console.log('Note: one payment failed (likely TX serialization). The succeeding one left a consistent state.')
    if (Math.abs(Number(final!.outstandingAmount)) < 0.01 && final!.status !== 'PAID') {
      console.log('✗ BUG: outstanding=0 but status =', final!.status)
      process.exit(1)
    } else if (final!.status === 'PARTIALLY_PAID' && Number(final!.outstandingAmount) > 0) {
      console.log('✓ PASS: only one payment got through, status correctly PARTIALLY_PAID')
    } else if (final!.status === 'PAID' && Number(final!.outstandingAmount) === 0) {
      console.log('✓ PASS: only one payment got through but cleared the invoice (impossible given amounts) — check logs')
    }
  } else {
    if (Math.abs(Number(final!.outstandingAmount)) < 0.01 && final!.status !== 'PAID') {
      console.log('✗ BUG: outstanding=0 but status =', final!.status)
      process.exit(1)
    }
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
    await pool.end()
  })
