import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireAuthFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'
import { Prisma } from '@prisma/client'

interface RouteParams {
  params: Promise<{ id: string }>
}

const VALID_PAYMENT_METHODS = ['BANK_TRANSFER', 'CASH'] as const

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireAuthFromRequest(request)
    const { id } = await params

    const body = await request.json()
    const { paymentMethod } = body

    if (!paymentMethod || !VALID_PAYMENT_METHODS.includes(paymentMethod)) {
      return apiBadRequest(`paymentMethod must be one of: ${VALID_PAYMENT_METHODS.join(', ')}`)
    }

    const claim = await prisma.expenseClaim.findFirst({
      where: { id, organizationId: auth.organizationId },
    })

    if (!claim) {
      return apiNotFound('Expense claim not found')
    }

    if (claim.status !== 'FINANCE_APPROVED') {
      return apiBadRequest(
        'Only FINANCE_APPROVED claims can be paid. Current status: ' + claim.status,
      )
    }

    // Get current fiscal year
    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: { organizationId: auth.organizationId, isCurrent: true },
    })
    if (!fiscalYear) {
      return apiBadRequest('No current fiscal year found. Please configure a fiscal year first.')
    }

    // Find the Expense Claims Payable account (2107)
    const claimsPayableAccount = await prisma.account.findFirst({
      where: { organizationId: auth.organizationId, code: '2107' },
    })
    if (!claimsPayableAccount) {
      return apiBadRequest(
        'Expense Claims Payable account (2107) not found. Please set up Chart of Accounts.',
      )
    }

    // Find the payment account based on method
    const paymentAccountCode = paymentMethod === 'BANK_TRANSFER' ? '1111' : '1101'
    const paymentAccount = await prisma.account.findFirst({
      where: { organizationId: auth.organizationId, code: paymentAccountCode },
    })
    if (!paymentAccount) {
      return apiBadRequest(
        `Payment account (${paymentAccountCode}) not found. Please set up Chart of Accounts.`,
      )
    }

    const now = new Date()
    const payAmount = claim.netPayable
      ? new Prisma.Decimal(Number(claim.netPayable))
      : new Prisma.Decimal(Number(claim.approvedAmount || claim.totalAmount))

    const result = await prisma.$transaction(async (tx) => {
      // Create payment JE: DR Claims Payable, CR Bank/Cash
      const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')

      const je = await tx.journalEntry.create({
        data: {
          entryNo,
          date: now,
          description: `Payment for expense claim ${claim.claimNo}`,
          reference: claim.claimNo,
          fiscalYearId: fiscalYear.id,
          projectId: claim.projectId,
          grantId: claim.grantId,
          totalDebit: payAmount,
          totalCredit: payAmount,
          status: 'APPROVED',
          isAutoGenerated: true,
          sourceModule: 'expense_claim',
          sourceId: claim.id,
          createdById: auth.userId,
          approvedById: auth.userId,
          approvedAt: now,
          postedAt: now,
          lines: {
            create: [
              {
                accountId: claimsPayableAccount.id,
                description: `Clear expense claim ${claim.claimNo}`,
                debit: payAmount,
                credit: new Prisma.Decimal(0),
                projectId: claim.projectId,
              },
              {
                accountId: paymentAccount.id,
                description: `Payment for expense claim ${claim.claimNo}`,
                debit: new Prisma.Decimal(0),
                credit: payAmount,
                projectId: claim.projectId,
              },
            ],
          },
        },
      })

      // Create voucher
      const voucherType = paymentMethod === 'BANK_TRANSFER' ? 'BANK' : 'CASH'
      const voucherEntity =
        paymentMethod === 'BANK_TRANSFER' ? 'voucher_bv' : 'voucher_cv'
      const voucherNo = await generateNextNumber(auth.organizationId, voucherEntity)

      // Find employee name for payee
      const employee = await tx.employee.findFirst({
        where: { id: claim.employeeId },
        select: { fullName: true },
      })
      const payeeName = employee ? employee.fullName : 'Employee'

      const voucher = await tx.voucher.create({
        data: {
          organizationId: auth.organizationId,
          voucherNo,
          type: voucherType,
          date: now,
          description: `Payment for expense claim ${claim.claimNo}: ${claim.purpose}`,
          amount: payAmount,
          payee: payeeName,
          projectId: claim.projectId,
          grantId: claim.grantId,
          journalEntryId: je.id,
          status: 'APPROVED',
          preparedById: auth.userId,
          approvedById: auth.userId,
          approvedAt: now,
        },
      })

      // If advance linked, update advance settlement
      if (claim.advanceId && claim.advanceDeducted && Number(claim.advanceDeducted) > 0) {
        const advance = await tx.employeeAdvance.findFirst({
          where: { id: claim.advanceId },
        })
        if (advance) {
          const currentSettled = Number(advance.settledAmount || 0)
          const newSettled = currentSettled + Number(claim.advanceDeducted)
          const disbursed = Number(advance.disbursedAmount || 0)
          const newStatus = newSettled >= disbursed ? 'SETTLED' : 'PARTIALLY_SETTLED'

          await tx.employeeAdvance.update({
            where: { id: claim.advanceId },
            data: {
              settledAmount: new Prisma.Decimal(newSettled),
              status: newStatus,
              settledAt: newStatus === 'SETTLED' ? now : undefined,
            },
          })
        }
      }

      // Update claim
      const updated = await tx.expenseClaim.update({
        where: { id },
        data: {
          status: 'PAID',
          paymentMethod,
          paidAt: now,
          voucherId: voucher.id,
        },
      })

      return updated
    })

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'UPDATE',
      module: 'finance',
      resource: 'expense_claim',
      resourceId: id,
      description: `Paid expense claim ${claim.claimNo} via ${paymentMethod}`,
      oldValues: { status: 'FINANCE_APPROVED' },
      newValues: { status: 'PAID', paymentMethod, paidAt: now },
      ...auditCtx,
    })

    return apiSuccess(result)
  } catch (error) {
    return handleRouteError(error)
  }
}
