import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireRoleFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import { Prisma } from '@prisma/client'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'

interface RouteParams {
  params: Promise<{ id: string }>
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireRoleFromRequest(request, [
      'ADMIN',
      'FINANCE_ADMIN',
      'FINANCE_HEAD',
    ])
    const { id } = await params

    // Fetch fund receipt with tenant isolation via organizationId
    const receipt = await prisma.fundReceipt.findFirst({
      where: {
        id,
        organizationId: auth.organizationId,
        deletedAt: null,
      },
      include: {
        grant: {
          select: {
            id: true,
            grantNo: true,
            title: true,
            donorId: true,
            donor: { select: { id: true, name: true } },
          },
        },
        bankAccount: {
          select: {
            id: true,
            accountName: true,
            accountCode: true,
          },
        },
      },
    })

    if (!receipt) {
      return apiNotFound('Fund receipt not found')
    }

    if (receipt.status !== 'PENDING') {
      return apiBadRequest(
        `Only PENDING fund receipts can be confirmed. Current status: ${receipt.status}`
      )
    }

    // Find current fiscal year for org
    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: {
        organizationId: auth.organizationId,
        isCurrent: true,
      },
      select: { id: true },
    })

    if (!fiscalYear) {
      return apiBadRequest('No active fiscal year found for this organization')
    }

    // Find the bank account's corresponding Account (chart of accounts)
    const bankChartAccount = await prisma.account.findFirst({
      where: {
        organizationId: auth.organizationId,
        isBankAccount: true,
        deletedAt: null,
      },
      select: { id: true },
    })

    // Find a grant income account
    const grantIncomeAccount = await prisma.account.findFirst({
      where: {
        organizationId: auth.organizationId,
        type: 'INCOME',
        deletedAt: null,
        OR: [
          { name: { contains: 'grant', mode: 'insensitive' } },
          { name: { contains: 'donor', mode: 'insensitive' } },
          { fundCode: { not: null } },
        ],
      },
      select: { id: true },
    })

    if (!bankChartAccount || !grantIncomeAccount) {
      return apiBadRequest(
        'Required chart of accounts not configured. Ensure a bank account and grant income account exist.'
      )
    }

    const amountInBDT = Number(receipt.amountInBDT)

    // Generate journal entry number
    const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')

    // Perform all updates in a transaction
    const result = await prisma.$transaction(async (tx) => {
      // 1. Create auto-posted JournalEntry: DR Bank, CR Grant Income
      const journalEntry = await tx.journalEntry.create({
        data: {
          entryNo,
          date: receipt.date,
          description: `Fund receipt ${receipt.receiptNo} — ${receipt.grant.title} (${receipt.grant.donor.name})`,
          fiscalYearId: fiscalYear.id,
          projectId: null,
          grantId: receipt.grantId,
          currencyCode: receipt.currencyCode,
          exchangeRate: receipt.exchangeRate,
          totalDebit: new Prisma.Decimal(amountInBDT),
          totalCredit: new Prisma.Decimal(amountInBDT),
          status: 'APPROVED',
          isAutoGenerated: true,
          sourceModule: 'donor',
          sourceId: receipt.id,
          createdById: auth.userId,
          approvedById: auth.userId,
          approvedAt: new Date(),
          postedAt: new Date(),
          lines: {
            create: [
              {
                accountId: bankChartAccount.id,
                description: `Fund received from ${receipt.grant.donor.name} — ${receipt.grant.title}`,
                debit: new Prisma.Decimal(amountInBDT),
                credit: new Prisma.Decimal(0),
              },
              {
                accountId: grantIncomeAccount.id,
                description: `Grant income — ${receipt.grant.title}`,
                debit: new Prisma.Decimal(0),
                credit: new Prisma.Decimal(amountInBDT),
              },
            ],
          },
        },
      })

      // 2. Update fund receipt status and link journal entry
      const updatedReceipt = await tx.fundReceipt.update({
        where: { id },
        data: {
          status: 'CONFIRMED',
          journalEntryId: journalEntry.id,
        },
      })

      // 3. Update Grant disbursedAmount
      await tx.grant.update({
        where: { id: receipt.grantId },
        data: {
          disbursedAmount: { increment: new Prisma.Decimal(amountInBDT) },
        },
      })

      // 4. Update BankAccount currentBalance
      await tx.bankAccount.update({
        where: { id: receipt.bankAccountId },
        data: {
          currentBalance: { increment: new Prisma.Decimal(amountInBDT) },
        },
      })

      return { updatedReceipt, journalEntry }
    })

    // Log audit
    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'UPDATE',
      module: 'donor',
      resource: 'fund_receipt',
      resourceId: id,
      description: `Confirmed fund receipt ${receipt.receiptNo} (${amountInBDT} BDT). Journal entry ${entryNo} auto-created.`,
      oldValues: { status: 'PENDING' },
      newValues: {
        status: 'CONFIRMED',
        journalEntryId: result.journalEntry.id,
        amountInBDT,
      },
      ...auditCtx,
    })

    return apiSuccess({
      ...result.updatedReceipt,
      journalEntry: {
        id: result.journalEntry.id,
        entryNo: result.journalEntry.entryNo,
      },
    })
  } catch (error) {
    return handleRouteError(error)
  }
}
