import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireAuthFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import { Prisma } from '@prisma/client'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'

interface RouteParams {
  params: Promise<{ id: string }>
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireAuthFromRequest(request)
    const { id } = await params

    const disposal = await prisma.assetDisposal.findFirst({
      where: {
        id,
        asset: { category: { organizationId: auth.organizationId } },
      },
    })

    if (!disposal) {
      return apiNotFound('Disposal record not found')
    }

    if (disposal.approvedAt) {
      return apiBadRequest('Disposal already approved')
    }

    const now = new Date()

    const [updated] = await prisma.$transaction([
      prisma.assetDisposal.update({
        where: { id },
        data: {
          approvedById: auth.userId,
          approvedAt: now,
        },
      }),
      prisma.asset.update({
        where: { id: disposal.assetId },
        data: {
          isActive: false,
          disposedAt: now,
          condition: 'DISPOSED',
        },
      }),
    ])

    // Auto-create JE for disposal if recovery amount > 0 and accounts exist
    let journalEntryId: string | null = null
    const recoveryAmount = Number(disposal.recoveryAmount)
    const bookValue = Number(disposal.bookValueAtDisposal)

    if (recoveryAmount > 0 || bookValue > 0) {
      const fiscalYear = await prisma.fiscalYear.findFirst({
        where: { organizationId: auth.organizationId, isCurrent: true },
        select: { id: true },
      })

      if (fiscalYear) {
        // Find Cash/Bank account (code '1101') and Asset account (code starting with '1')
        const bankAccount = await prisma.account.findFirst({
          where: {
            organizationId: auth.organizationId,
            code: '1101',
            isGroup: false,
            deletedAt: null,
          },
          select: { id: true },
        })

        // Find an asset account — any non-group account with code starting with '15' (Fixed Assets)
        const assetAccount = await prisma.account.findFirst({
          where: {
            organizationId: auth.organizationId,
            code: { startsWith: '15' },
            isGroup: false,
            deletedAt: null,
          },
          select: { id: true },
        })

        if (bankAccount && assetAccount && recoveryAmount > 0) {
          const gainLoss = recoveryAmount - bookValue
          const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')

          // Simplified JE: DR Cash = recoveryAmount, CR Asset = recoveryAmount
          // Gain/loss is captured in the description
          const je = await prisma.journalEntry.create({
            data: {
              entryNo,
              date: now,
              description: `Asset disposal ${disposal.disposalNo}${gainLoss !== 0 ? ` (${gainLoss > 0 ? 'gain' : 'loss'}: ${Math.abs(gainLoss).toFixed(2)})` : ''}`,
              fiscalYearId: fiscalYear.id,
              totalDebit: new Prisma.Decimal(recoveryAmount),
              totalCredit: new Prisma.Decimal(recoveryAmount),
              status: 'APPROVED',
              isAutoGenerated: true,
              sourceModule: 'asset',
              sourceId: disposal.id,
              createdById: auth.userId,
              approvedById: auth.userId,
              approvedAt: now,
              postedAt: now,
              lines: {
                create: [
                  {
                    accountId: bankAccount.id,
                    description: `Disposal recovery — ${disposal.disposalNo}`,
                    debit: new Prisma.Decimal(recoveryAmount),
                    credit: new Prisma.Decimal(0),
                  },
                  {
                    accountId: assetAccount.id,
                    description: `Asset disposed — ${disposal.disposalNo}`,
                    debit: new Prisma.Decimal(0),
                    credit: new Prisma.Decimal(recoveryAmount),
                  },
                ],
              },
            },
          })

          journalEntryId = je.id

          // Store journalEntryId on disposal record
          await prisma.assetDisposal.update({
            where: { id },
            data: { journalEntryId: je.id },
          })
        }
        // If accounts not found, skip JE — disposal still approved
      }
    }

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'UPDATE',
      module: 'asset',
      resource: 'asset_disposal',
      resourceId: id,
      description: `Approved disposal ${disposal.disposalNo}${journalEntryId ? ' with auto-created journal entry' : ''}`,
      newValues: { status: 'APPROVED', disposedAt: now, journalEntryId },
      ...auditCtx,
    })

    return apiSuccess({ ...updated, journalEntryId })
  } catch (error) {
    return handleRouteError(error)
  }
}
