import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireAuthFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import {
  apiCreated,
  apiPaginated,
  apiBadRequest,
  handleRouteError,
  parsePaginationParams,
} from '@/lib/api-response'
import { Prisma } from '@prisma/client'

export async function GET(request: NextRequest) {
  try {
    const auth = await requireAuthFromRequest(request)

    const url = new URL(request.url)
    const { page, limit, skip, search } = parsePaginationParams(url)

    const where: Record<string, unknown> = {
      fiscalYear: { organizationId: auth.organizationId },
      deletedAt: null,
    }

    if (search) {
      where.OR = [
        { entryNo: { contains: search, mode: 'insensitive' } },
        { description: { contains: search, mode: 'insensitive' } },
      ]
    }

    const status = url.searchParams.get('status')
    if (status) {
      where.status = status
    }

    const projectId = url.searchParams.get('projectId')
    if (projectId) {
      where.projectId = projectId
    }

    const grantId = url.searchParams.get('grantId')
    if (grantId) {
      where.grantId = grantId
    }

    const dateFrom = url.searchParams.get('dateFrom')
    const dateTo = url.searchParams.get('dateTo')
    if (dateFrom || dateTo) {
      const dateFilter: Record<string, Date> = {}
      if (dateFrom) dateFilter.gte = new Date(dateFrom)
      if (dateTo) dateFilter.lte = new Date(dateTo)
      where.date = dateFilter
    }

    const [entries, total] = await Promise.all([
      prisma.journalEntry.findMany({
        where,
        select: {
          id: true,
          entryNo: true,
          date: true,
          description: true,
          reference: true,
          fiscalYearId: true,
          projectId: true,
          grantId: true,
          currencyCode: true,
          exchangeRate: true,
          totalDebit: true,
          totalCredit: true,
          status: true,
          isAutoGenerated: true,
          sourceModule: true,
          notes: true,
          createdById: true,
          approvedById: true,
          approvedAt: true,
          postedAt: true,
          createdAt: true,
          updatedAt: true,
          _count: {
            select: { lines: true },
          },
        },
        orderBy: { date: 'desc' },
        skip,
        take: limit,
      }),
      prisma.journalEntry.count({ where }),
    ])

    return apiPaginated(entries, total, page, limit)
  } catch (error) {
    return handleRouteError(error)
  }
}

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuthFromRequest(request)

    const body = await request.json()
    const {
      date,
      description,
      reference,
      fiscalYearId,
      projectId,
      grantId,
      currencyCode,
      exchangeRate,
      notes,
      lines,
    } = body

    // Basic required fields
    if (!date || !description || !fiscalYearId) {
      return apiBadRequest('date, description, and fiscalYearId are required')
    }

    // Validate lines
    if (!Array.isArray(lines) || lines.length < 2) {
      return apiBadRequest('At least 2 journal entry lines are required')
    }

    // Validate each line: must have either debit > 0 or credit > 0 (not both, not neither)
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const debit = Number(line.debit || 0)
      const credit = Number(line.credit || 0)

      if (!line.accountId) {
        return apiBadRequest(`Line ${i + 1}: accountId is required`)
      }

      if (debit > 0 && credit > 0) {
        return apiBadRequest(`Line ${i + 1}: a line cannot have both debit and credit`)
      }

      if (debit <= 0 && credit <= 0) {
        return apiBadRequest(`Line ${i + 1}: a line must have either debit > 0 or credit > 0`)
      }
    }

    // Validate total debit equals total credit
    const totalDebit = lines.reduce((sum: number, l: { debit?: number }) => sum + Number(l.debit || 0), 0)
    const totalCredit = lines.reduce((sum: number, l: { credit?: number }) => sum + Number(l.credit || 0), 0)

    if (Math.abs(totalDebit - totalCredit) > 0.001) {
      return apiBadRequest(
        `Total debit (${totalDebit}) must equal total credit (${totalCredit})`
      )
    }

    // Validate fiscal year belongs to this org and is not closed
    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: {
        id: fiscalYearId,
        organizationId: auth.organizationId,
      },
    })

    if (!fiscalYear) {
      return apiBadRequest('Fiscal year not found in this organization')
    }

    if (fiscalYear.isClosed) {
      return apiBadRequest('Cannot create journal entry in a closed fiscal year')
    }

    // Validate all accountIds exist in same org and are not group accounts
    const accountIds = lines.map((l: { accountId: string }) => l.accountId)
    const accounts = await prisma.account.findMany({
      where: {
        id: { in: accountIds },
        organizationId: auth.organizationId,
        deletedAt: null,
      },
      select: { id: true, isGroup: true },
    })

    if (accounts.length !== new Set(accountIds).size) {
      return apiBadRequest('One or more account IDs are invalid or not found in this organization')
    }

    const groupAccounts = accounts.filter((a) => a.isGroup)
    if (groupAccounts.length > 0) {
      return apiBadRequest('Cannot post to group accounts. All accounts must be detail (non-group) accounts')
    }

    // Validate projectId if provided
    if (projectId) {
      const project = await prisma.project.findFirst({
        where: { id: projectId, organizationId: auth.organizationId },
      })
      if (!project) {
        return apiBadRequest('Invalid project ID')
      }
    }

    // Validate grantId if provided (Grant links to org through donor)
    if (grantId) {
      const grant = await prisma.grant.findFirst({
        where: { id: grantId, donor: { organizationId: auth.organizationId } },
      })
      if (!grant) {
        return apiBadRequest('Invalid grant ID')
      }
    }

    // Generate entry number
    const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')

    // Create journal entry with lines in a transaction
    const journalEntry = await prisma.$transaction(async (tx) => {
      const entry = await tx.journalEntry.create({
        data: {
          entryNo,
          date: new Date(date),
          description: description.trim(),
          reference: reference || null,
          fiscalYearId,
          projectId: projectId || null,
          grantId: grantId || null,
          currencyCode: currencyCode || 'BDT',
          exchangeRate: exchangeRate ? new Prisma.Decimal(exchangeRate) : new Prisma.Decimal(1),
          totalDebit: new Prisma.Decimal(totalDebit),
          totalCredit: new Prisma.Decimal(totalCredit),
          status: 'DRAFT',
          notes: notes || null,
          createdById: auth.userId,
          lines: {
            create: lines.map((line: {
              accountId: string
              description?: string
              debit?: number
              credit?: number
              projectId?: string
            }) => ({
              accountId: line.accountId,
              description: line.description || null,
              debit: new Prisma.Decimal(Number(line.debit || 0)),
              credit: new Prisma.Decimal(Number(line.credit || 0)),
              projectId: line.projectId || null,
            })),
          },
        },
        include: {
          lines: {
            include: {
              account: {
                select: { id: true, code: true, name: true },
              },
            },
          },
        },
      })

      return entry
    })

    // Log audit
    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'CREATE',
      module: 'finance',
      resource: 'journal_entry',
      resourceId: journalEntry.id,
      description: `Created journal entry ${entryNo}`,
      newValues: { entryNo, description, totalDebit, totalCredit, lineCount: lines.length },
      ...auditCtx,
    })

    return apiCreated(journalEntry)
  } catch (error) {
    return handleRouteError(error)
  }
}
