import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireAuthFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'
import { Prisma } from '@prisma/client'

interface RouteParams {
  params: Promise<{ id: string }>
}

const VALID_METHODS = ['BANK_TRANSFER', 'CASH'] as const

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireAuthFromRequest(request)
    const { id } = await params

    const body = await request.json()
    const { disbursementMethod, bankAccountId } = body

    if (!disbursementMethod || !VALID_METHODS.includes(disbursementMethod)) {
      return apiBadRequest(`disbursementMethod must be one of: ${VALID_METHODS.join(', ')}`)
    }

    if (disbursementMethod === 'BANK_TRANSFER' && !bankAccountId) {
      return apiBadRequest('bankAccountId is required for BANK_TRANSFER disbursement')
    }

    const advance = await prisma.employeeAdvance.findFirst({
      where: { id, organizationId: auth.organizationId },
    })

    if (!advance) {
      return apiNotFound('Advance not found')
    }

    if (advance.status !== 'APPROVED') {
      return apiBadRequest(
        'Only APPROVED advances can be disbursed. Current status: ' + advance.status,
      )
    }

    // Get current fiscal year
    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: { organizationId: auth.organizationId, isCurrent: true },
    })
    if (!fiscalYear) {
      return apiBadRequest('No current fiscal year found. Please configure a fiscal year first.')
    }

    // Find advance receivable account based on type
    const advanceAccountCode = advance.advanceType === 'TRAVEL' ? '1131' : '1132'
    const advanceAccount = await prisma.account.findFirst({
      where: { organizationId: auth.organizationId, code: advanceAccountCode },
    })
    if (!advanceAccount) {
      return apiBadRequest(
        `Advance Receivable account (${advanceAccountCode}) not found. Please set up Chart of Accounts.`,
      )
    }

    // Find payment account
    const paymentAccountCode = disbursementMethod === 'BANK_TRANSFER' ? '1111' : '1101'
    const paymentAccount = await prisma.account.findFirst({
      where: { organizationId: auth.organizationId, code: paymentAccountCode },
    })
    if (!paymentAccount) {
      return apiBadRequest(
        `Payment account (${paymentAccountCode}) not found. Please set up Chart of Accounts.`,
      )
    }

    // Validate bankAccountId if provided
    if (bankAccountId) {
      const bankAccount = await prisma.bankAccount.findFirst({
        where: { id: bankAccountId, organizationId: auth.organizationId },
      })
      if (!bankAccount) {
        return apiBadRequest('Bank account not found in this organization')
      }
    }

    const now = new Date()
    const disbursedAmount = new Prisma.Decimal(Number(advance.approvedAmount || advance.estimatedAmount))

    const result = await prisma.$transaction(async (tx) => {
      // Create JE: DR Advance Receivable, CR Bank/Cash
      const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')

      const je = await tx.journalEntry.create({
        data: {
          entryNo,
          date: now,
          description: `Advance disbursement ${advance.advanceNo}: ${advance.purpose}`,
          reference: advance.advanceNo,
          fiscalYearId: fiscalYear.id,
          projectId: advance.projectId,
          grantId: advance.grantId,
          totalDebit: disbursedAmount,
          totalCredit: disbursedAmount,
          status: 'APPROVED',
          isAutoGenerated: true,
          sourceModule: 'employee_advance',
          sourceId: advance.id,
          createdById: auth.userId,
          approvedById: auth.userId,
          approvedAt: now,
          postedAt: now,
          lines: {
            create: [
              {
                accountId: advanceAccount.id,
                description: `Advance to employee - ${advance.advanceNo}`,
                debit: disbursedAmount,
                credit: new Prisma.Decimal(0),
                projectId: advance.projectId,
              },
              {
                accountId: paymentAccount.id,
                description: `Disbursement for advance ${advance.advanceNo}`,
                debit: new Prisma.Decimal(0),
                credit: disbursedAmount,
                projectId: advance.projectId,
              },
            ],
          },
        },
      })

      // Create voucher
      const voucherType = disbursementMethod === 'BANK_TRANSFER' ? 'BANK' : 'CASH'
      const voucherEntity =
        disbursementMethod === 'BANK_TRANSFER' ? 'voucher_bv' : 'voucher_cv'
      const voucherNo = await generateNextNumber(auth.organizationId, voucherEntity)

      // Find employee name for payee
      const employee = await tx.employee.findFirst({
        where: { id: advance.employeeId },
        select: { fullName: true },
      })
      const payeeName = employee ? employee.fullName : 'Employee'

      const voucher = await tx.voucher.create({
        data: {
          organizationId: auth.organizationId,
          voucherNo,
          type: voucherType,
          date: now,
          description: `Advance disbursement ${advance.advanceNo}: ${advance.purpose}`,
          amount: disbursedAmount,
          payee: payeeName,
          projectId: advance.projectId,
          grantId: advance.grantId,
          bankAccountId: bankAccountId || null,
          journalEntryId: je.id,
          status: 'APPROVED',
          preparedById: auth.userId,
          approvedById: auth.userId,
          approvedAt: now,
        },
      })

      // Update advance
      const updated = await tx.employeeAdvance.update({
        where: { id },
        data: {
          status: 'DISBURSED',
          disbursedAmount,
          disbursedAt: now,
          disbursementMethod,
          bankAccountId: bankAccountId || null,
          disbursementVoucherId: voucher.id,
          disbursementJournalId: je.id,
        },
      })

      return updated
    })

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'UPDATE',
      module: 'finance',
      resource: 'employee_advance',
      resourceId: id,
      description: `Disbursed advance ${advance.advanceNo} via ${disbursementMethod}`,
      oldValues: { status: 'APPROVED' },
      newValues: {
        status: 'DISBURSED',
        disbursedAmount: Number(disbursedAmount),
        disbursementMethod,
        disbursedAt: now,
      },
      ...auditCtx,
    })

    return apiSuccess(result)
  } catch (error) {
    return handleRouteError(error)
  }
}
