import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireRoleFromRequest } from '@/lib/auth'
import { logAudit, getAuditContext } from '@/lib/audit'
import { generateNextNumber } from '@/lib/number-sequence'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'
import { Prisma } from '@prisma/client'

interface RouteParams {
  params: Promise<{ id: string }>
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireRoleFromRequest(request, 'ADMIN')
    const { id } = await params

    const grn = await prisma.goodsReceipt.findFirst({
      where: {
        id,
        vendor: { organizationId: auth.organizationId },
      },
      include: {
        vendor: { select: { companyName: true } },
        purchaseOrder: { select: { poNo: true } },
        lines: {
          include: {
            poLine: {
              select: {
                unitPrice: true,
                description: true,
                accountId: true,
                budgetLineId: true,
                businessUnitId: true,
                costCenterId: true,
                fundClassId: true,
                projectId: true,
                grantId: true,
              },
            },
          },
        },
      },
    })

    if (!grn) {
      return apiNotFound('Goods receipt not found')
    }

    if (grn.status !== 'ACCEPTED' && grn.status !== 'PARTIAL') {
      return apiBadRequest('Only ACCEPTED or PARTIAL goods receipts can be posted to accounting')
    }

    const existingEntry = await prisma.journalEntry.findFirst({
      where: {
        sourceModule: 'PROCUREMENT_GRN',
        sourceId: grn.id,
        deletedAt: null,
      },
      select: { id: true, entryNo: true, status: true },
    })

    if (existingEntry) {
      return apiBadRequest(`Accounting already posted for this GRN as ${existingEntry.entryNo}`)
    }

    const amount = grn.lines.reduce(
      (sum, line) => sum + Number(line.quantityAccepted) * Number(line.poLine.unitPrice),
      0
    )

    if (amount <= 0) {
      return apiBadRequest('Accepted amount must be greater than zero')
    }

    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: {
        organizationId: auth.organizationId,
        startDate: { lte: grn.date },
        endDate: { gte: grn.date },
        isClosed: false,
      },
      orderBy: { startDate: 'desc' },
    })

    if (!fiscalYear) {
      return apiBadRequest('No open fiscal year found for the GRN date')
    }

    const [fixedAssetAccount, accountsPayableAccount] = await Promise.all([
      prisma.account.findFirst({
        where: {
          organizationId: auth.organizationId,
          code: '1204',
          isGroup: false,
          deletedAt: null,
        },
      }),
      prisma.account.findFirst({
        where: {
          organizationId: auth.organizationId,
          code: '2101',
          isGroup: false,
          deletedAt: null,
        },
      }),
    ])

    if (!fixedAssetAccount) {
      return apiBadRequest('Fixed asset account 1204 not found')
    }

    if (!accountsPayableAccount) {
      return apiBadRequest('Accounts payable account 2101 not found')
    }

    const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')
    const debitLines = grn.lines
      .map((line) => ({
        amount: Number(line.quantityAccepted) * Number(line.poLine.unitPrice),
        poLine: line.poLine,
      }))
      .filter((line) => line.amount > 0)

    const firstDebitLine = debitLines[0]?.poLine

    const entry = await prisma.journalEntry.create({
      data: {
        entryNo,
        date: grn.date,
        description: `Fixed asset receipt from ${grn.grnNo}`,
        reference: `${grn.purchaseOrder.poNo} / ${grn.grnNo}`,
        fiscalYearId: fiscalYear.id,
        projectId: firstDebitLine?.projectId || null,
        grantId: firstDebitLine?.grantId || null,
        businessUnitId: firstDebitLine?.businessUnitId || null,
        totalDebit: new Prisma.Decimal(amount),
        totalCredit: new Prisma.Decimal(amount),
        status: 'APPROVED',
        isAutoGenerated: true,
        sourceModule: 'PROCUREMENT_GRN',
        sourceId: grn.id,
        notes: `Auto-posted from procurement goods receipt for ${grn.vendor.companyName}`,
        createdById: auth.userId,
        approvedById: auth.userId,
        approvedAt: new Date(),
        postedAt: new Date(),
        lines: {
          create: [
            ...debitLines.map((line) => ({
              accountId: line.poLine.accountId || fixedAssetAccount.id,
              budgetLineId: line.poLine.budgetLineId || null,
              projectId: line.poLine.projectId || null,
              businessUnitId: line.poLine.businessUnitId || null,
              costCenterId: line.poLine.costCenterId || null,
              fundClassId: line.poLine.fundClassId || null,
              description: `DR fixed assets for ${grn.grnNo} - ${line.poLine.description}`,
              debit: new Prisma.Decimal(line.amount),
              credit: new Prisma.Decimal(0),
            })),
            {
              accountId: accountsPayableAccount.id,
              description: `CR accounts payable for ${grn.vendor.companyName}`,
              projectId: firstDebitLine?.projectId || null,
              businessUnitId: firstDebitLine?.businessUnitId || null,
              costCenterId: firstDebitLine?.costCenterId || null,
              fundClassId: firstDebitLine?.fundClassId || null,
              debit: new Prisma.Decimal(0),
              credit: new Prisma.Decimal(amount),
            },
          ],
        },
      },
      include: {
        lines: {
          include: {
            account: { select: { code: true, name: true } },
          },
        },
      },
    })

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'CREATE',
      module: 'FINANCE',
      resource: 'JournalEntry',
      resourceId: entry.id,
      description: `Posted accounting entry ${entryNo} for goods receipt ${grn.grnNo}`,
      newValues: { entryNo, grnId: grn.id, amount },
      ...auditCtx,
    })

    return apiSuccess(entry)
  } catch (error) {
    return handleRouteError(error)
  }
}
