import { NextRequest } from 'next/server'
import { prisma } from '@/lib/db'
import { requireRoleFromRequest } from '@/lib/auth'
import { generateNextNumber } from '@/lib/number-sequence'
import { logAudit, getAuditContext } from '@/lib/audit'
import { Prisma } from '@prisma/client'
import {
  apiSuccess,
  apiBadRequest,
  apiNotFound,
  handleRouteError,
} from '@/lib/api-response'

interface RouteParams {
  params: Promise<{ id: string }>
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const auth = await requireRoleFromRequest(request, 'ADMIN')
    const { id } = await params

    const run = await prisma.payrollRun.findUnique({
      where: { id },
      include: {
        entries: true,
      },
    })
    if (!run) return apiNotFound('Payroll run not found')

    if (run.status !== 'PROCESSED') {
      return apiBadRequest('Payroll run must be processed before approval')
    }

    // Calculate totals from payroll entries
    const totalGross = run.entries.reduce((sum, e) => sum + Number(e.grossSalary), 0)
    const totalNet = run.entries.reduce((sum, e) => sum + Number(e.netSalary), 0)

    // Attempt to create auto JE
    let journalEntryId: string | null = null

    // Find current fiscal year
    const fiscalYear = await prisma.fiscalYear.findFirst({
      where: { organizationId: auth.organizationId, isCurrent: true },
      select: { id: true },
    })

    if (fiscalYear && totalGross > 0) {
      // Find salary expense account (code '5100') and bank account (code '1101')
      const salaryAccount = await prisma.account.findFirst({
        where: {
          organizationId: auth.organizationId,
          code: '5100',
          isGroup: false,
          deletedAt: null,
        },
        select: { id: true },
      })

      const bankAccount = await prisma.account.findFirst({
        where: {
          organizationId: auth.organizationId,
          code: '1101',
          isGroup: false,
          deletedAt: null,
        },
        select: { id: true },
      })

      if (salaryAccount && bankAccount) {
        const entryNo = await generateNextNumber(auth.organizationId, 'journal_entry')
        const now = new Date()

        const je = await prisma.journalEntry.create({
          data: {
            entryNo,
            date: now,
            description: `Payroll ${run.runNo} — ${run.month}/${run.year} (${run.entries.length} employees)`,
            fiscalYearId: fiscalYear.id,
            totalDebit: new Prisma.Decimal(totalGross),
            totalCredit: new Prisma.Decimal(totalGross),
            status: 'APPROVED',
            isAutoGenerated: true,
            sourceModule: 'payroll',
            sourceId: run.id,
            createdById: auth.userId,
            approvedById: auth.userId,
            approvedAt: now,
            postedAt: now,
            lines: {
              create: [
                {
                  accountId: salaryAccount.id,
                  description: `Salary expense — ${run.month}/${run.year}`,
                  debit: new Prisma.Decimal(totalGross),
                  credit: new Prisma.Decimal(0),
                },
                {
                  accountId: bankAccount.id,
                  description: `Salary payment — ${run.month}/${run.year}`,
                  debit: new Prisma.Decimal(0),
                  credit: new Prisma.Decimal(totalGross),
                },
              ],
            },
          },
        })

        journalEntryId = je.id
      }
      // If accounts not found, skip JE creation — payroll still gets approved
    }

    const updated = await prisma.payrollRun.update({
      where: { id },
      data: {
        status: 'APPROVED',
        approvedById: auth.userId,
        approvedAt: new Date(),
        ...(journalEntryId && { journalEntryId }),
      },
    })

    const auditCtx = getAuditContext(request)
    await logAudit({
      organizationId: auth.organizationId,
      userId: auth.userId,
      action: 'UPDATE',
      module: 'hr',
      resource: 'payroll_run',
      resourceId: id,
      description: `Approved payroll run ${run.runNo}${journalEntryId ? ' with auto-created journal entry' : ''}`,
      oldValues: { status: 'PROCESSED' },
      newValues: { status: 'APPROVED', journalEntryId },
      ...auditCtx,
    })

    return apiSuccess(updated)
  } catch (error) {
    return handleRouteError(error)
  }
}
